# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchParty', '0002_auto_20190717_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosting', to='watchParty.User'),
            preserve_default=False,
        ),
    ]
